#include "../gl.h"

//GLint glshim_glRenderMode(GLenum mode);
//void glshim_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha);
void glshim_glBlendEquationSeparatei(GLuint buf, GLenum modeRGB, GLenum modeAlpha);
//void glshim_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void glshim_glBlendFuncSeparatei(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
void glshim_glColorMaterial(GLenum face, GLenum mode);
void glshim_glCopyPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum type);
void glshim_glDrawBuffer(GLenum mode);
void glshim_glEdgeFlag(GLboolean flag);
void glshim_glFogCoordd(GLdouble coord);
void glshim_glFogCoorddv(const GLdouble *coord);
void glshim_glFogCoordf(GLfloat coord);
void glshim_glFogCoordfv(const GLfloat *coord);
//void glshim_glGetTexImage(GLenum target, GLint level, GLenum format, GLenum type, GLvoid * img);
//void glshim_glGetTexLevelParameterfv(GLenum target, GLint level, GLenum pname, GLfloat *params);
//void glshim_glGetTexLevelParameteriv(GLenum target, GLint level, GLenum pname, GLint *params);
void glshim_glIndexf(GLfloat c);
void glshim_glLightModeli(GLenum pname, GLint param);
void glshim_glPolygonStipple(const GLubyte *mask);
void glshim_glReadBuffer(GLenum mode);
void glshim_glSecondaryColor3f(GLfloat r, GLfloat g, GLfloat b);
void glshim_glColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table);
//void glshim_glIndexPointer(GLenum  type,  GLsizei  stride,  const GLvoid *  pointer);

void glshim_glAccum(GLenum op, GLfloat value);
void glshim_glPrioritizeTextures(GLsizei n, const GLuint *textures, const GLclampf *priorities);
void glshim_glPixelMapfv(GLenum map, GLsizei mapsize, const GLfloat *values);
void glshim_glPixelMapuiv(GLenum map,GLsizei mapsize, const GLuint *values);
void glshim_glPixelMapusv(GLenum map,GLsizei mapsize, const GLushort *values);
void glshim_glPassThrough(GLfloat token);
void glshim_glIndexMask(GLuint mask);
void glshim_glGetPixelMapfv(GLenum map, GLfloat *data);
void glshim_glGetPixelMapuiv(GLenum map, GLuint *data);
void glshim_glGetPixelMapusv(GLenum map, GLushort *data);
void glshim_glClearIndex(GLfloat c);
void glshim_glGetPolygonStipple(GLubyte *pattern);
void glshim_glFeedbackBuffer(GLsizei size, GLenum type, GLfloat *buffer);
void glshim_glEdgeFlagv(GLboolean *flag);
