#!/bin/bash -ux
cd "$(dirname "$0")"

base=../src/
gles=$(ls -1 yml/*-1.1.yml | tr '\n' ',' | sed -e 's/,$//')

./gen.py "$gles" gleswrap.c.j2 gleswrap.c gles.h > "$base/gl/wrap/gles.c"
./gen.py "$gles" glwrap.h.j2 gleswrap.h ../gl.h > "$base/gl/wrap/gles.h"
./gen.py "$gles" glxfuncs.j2 glxfuncs.inc ../gl/gl.h > "$base/glx/glxfuncs.inc"

cats="VERSION_1_0,VERSION_1_1,VERSION_1_2,VERSION_1_3,VERSION_1_4,VERSION_1_5"

./gen.py --deep --cats "$cats" 'yml/opengl.yml' glwrap.h.j2 gl.h "<GL/gl.h>" "<GL/glx.h>" > "$base/proxy/gl.h"
./gen.py --deep --cats "$cats" 'yml/opengl.yml' client.c.j2 gl.c gl.h > "$base/proxy/gl.c"
