#include "wrap/gles.h"
#include "loader.h"

#define INIT_EGL(name) \
    name##_PTR name; \

#define INIT_GLES_FPE(name) \
    name##_PTR  fpe_##name; \

#define INIT_GLES(name) \
    name##_PTR (name); \

#define INIT_GLES_OR_OES(name) \
    name##_PTR (name); \

#define INIT_GLES_EXT(name) \
    name##_PTR (name); \

#define INIT_GLES_OES(name) \
    name##_PTR (name); \

#define ALL_FUNCTIONS() \
INIT_EGL(eglGetProcAddress) \
INIT_GLES(glCreateShader); \
INIT_GLES(glShaderSource); \
INIT_GLES(glCompileShader); \
INIT_GLES(glGetShaderiv); \
INIT_GLES(glDeleteShader); \
INIT_GLES(glGetError); \
INIT_GLES(glGetShaderInfoLog); \
INIT_GLES(glGetString); \
INIT_GLES(glGetIntegerv); \
INIT_GLES_OR_OES(glBlendColor); \
INIT_GLES(glGetShaderPrecisionFormat); \
INIT_GLES(glFinish); \
INIT_GLES(glReadPixels); \
INIT_GLES(glTexParameterf); \
INIT_GLES(glEnable); \
INIT_GLES_FPE(glEnable); \
INIT_GLES(glDisable); \
INIT_GLES_FPE(glDisable); \
INIT_GLES_OR_OES(glGenFramebuffers); \
INIT_GLES(glDepthFunc); \
INIT_GLES(glDepthMask); \
INIT_GLES(glDepthRangef); \
INIT_GLES(glClearDepthf); \
INIT_GLES(glClientActiveTexture); \
INIT_GLES_FPE(glClientActiveTexture); \
INIT_GLES_OES(glDrawTexf); \
INIT_GLES(glTexParameteriv); \
INIT_GLES(glVertexPointer); \
INIT_GLES_FPE(glVertexPointer); \
INIT_GLES(glTexCoordPointer); \
INIT_GLES_FPE(glTexCoordPointer); \
INIT_GLES(glDrawArrays); \
INIT_GLES_FPE(glDrawArrays); \
INIT_GLES(glBindAttribLocation); \
INIT_GLES(glAttachShader); \
INIT_GLES(glCreateProgram); \
INIT_GLES(glLinkProgram); \
INIT_GLES(glGetProgramiv); \
INIT_GLES(glGetUniformLocation); \
INIT_GLES(glUniform1i); \
INIT_GLES(glUseProgram); \
INIT_GLES(glBindTexture); \
INIT_GLES(glActiveTexture); \
INIT_GLES_FPE(glNormal3f); \
INIT_GLES(glNormal3f); \
INIT_GLES_FPE(glColor4f); \
INIT_GLES(glColor4f); \
INIT_GLES(glGenBuffers); \
INIT_GLES(glBufferData); \
INIT_GLES(glBindBuffer); \
INIT_GLES(glBufferSubData); \
INIT_GLES(glFlush); \
INIT_GLES(glShadeModel); \
INIT_GLES_FPE(glAlphaFunc); \
INIT_GLES(glAlphaFunc); \
INIT_GLES(glLogicOp); \
INIT_GLES(glColorMask); \
INIT_GLES(glClear); \
INIT_GLES(glDeleteBuffers); \
INIT_GLES_FPE(glMatrixMode); \
INIT_GLES(glMatrixMode); \
INIT_GLES(glLoadMatrixf); \
INIT_GLES(glLoadIdentity); \
INIT_GLES(glUniform1fv); \
INIT_GLES(glUniform2fv); \
INIT_GLES(glUniform3fv); \
INIT_GLES(glUniform4fv); \
INIT_GLES(glUniform1iv); \
INIT_GLES(glUniform2iv); \
INIT_GLES(glUniform3iv); \
INIT_GLES(glUniform4iv); \
INIT_GLES(glUniformMatrix2fv); \
INIT_GLES(glUniformMatrix3fv); \
INIT_GLES(glUniformMatrix4fv); \
INIT_GLES(glTexImage2D); \
INIT_GLES(glTexSubImage2D); \
INIT_GLES(glTexParameteri); \
INIT_GLES(glViewport); \
INIT_GLES(glScissor); \
INIT_GLES(glGenTextures); \
INIT_GLES(glTexParameterfv); \
INIT_GLES_OR_OES(glGenerateMipmap); \
INIT_GLES(glDeleteTextures); \
INIT_GLES(glPixelStorei); \
INIT_GLES_OES(glTexGeni); \
INIT_GLES_OES(glTexGenfv); \
INIT_GLES(glCompressedTexImage2D); \
INIT_GLES(glCompressedTexSubImage2D); \
INIT_GLES(glDeleteProgram); \
INIT_GLES(glDetachShader); \
INIT_GLES(glGetProgramInfoLog); \
INIT_GLES(glGetActiveUniform); \
INIT_GLES(glGetActiveAttrib); \
INIT_GLES(glGetAttribLocation); \
INIT_GLES_OES(glProgramBinary); \
INIT_GLES_OES(glGetProgramBinary); \
INIT_GLES(glValidateProgram); \
INIT_GLES(glIsEnabled); \
INIT_GLES_OR_OES(glBlendFuncSeparate); \
INIT_GLES_OR_OES(glBlendEquationSeparate); \
INIT_GLES(glBlendFunc); \
INIT_GLES_OR_OES(glBlendEquation); \
INIT_GLES_FPE(glPointParameterfv); \
INIT_GLES(glPointParameterfv); \
INIT_GLES_FPE(glPointSize); \
INIT_GLES(glPointSize); \
INIT_GLES(glCullFace); \
INIT_GLES(glFrontFace); \
INIT_GLES_FPE(glLightModelf); \
INIT_GLES(glLightModelf); \
INIT_GLES_FPE(glLightModelfv); \
INIT_GLES(glLightModelfv); \
INIT_GLES_FPE(glLightfv); \
INIT_GLES(glLightfv); \
INIT_GLES_FPE(glMaterialfv); \
INIT_GLES(glMaterialfv); \
INIT_GLES_FPE(glMaterialf); \
INIT_GLES(glMaterialf); \
INIT_GLES(glHint); \
INIT_GLES_OR_OES(glDeleteRenderbuffers); \
INIT_GLES_OR_OES(glDeleteFramebuffers); \
INIT_GLES(glEnableClientState); \
INIT_GLES(glDisableClientState); \
INIT_GLES(glDrawElements); \
INIT_GLES_FPE(glDrawElements); \
INIT_GLES(glVertexAttrib4fv); \
INIT_GLES(glEnableVertexAttribArray); \
INIT_GLES(glDisableVertexAttribArray); \
INIT_GLES(glVertexAttribPointer); \
INIT_GLES(glVertexAttribIPointer); \
INIT_GLES_OR_OES(glBindFramebuffer); \
INIT_GLES_OR_OES(glFramebufferTexture2D); \
INIT_GLES(glStencilMask); \
INIT_GLES_OR_OES(glStencilMaskSeparate); \
INIT_GLES(glStencilFunc); \
INIT_GLES_OR_OES(glStencilFuncSeparate); \
INIT_GLES(glStencilOp); \
INIT_GLES_OR_OES(glStencilOpSeparate); \
INIT_GLES(glClearStencil); \
INIT_GLES(glTexEnvf); \
INIT_GLES(glTexEnvfv); \
INIT_GLES(glGetTexEnviv); \
INIT_GLES(glClipPlanef); \
INIT_GLES_OR_OES(glIsFramebuffer); \
INIT_GLES_OR_OES(glCheckFramebufferStatus); \
INIT_GLES_OR_OES(glGenRenderbuffers); \
INIT_GLES_OR_OES(glFramebufferRenderbuffer); \
INIT_GLES_OR_OES(glGetFramebufferAttachmentParameteriv); \
INIT_GLES_OR_OES(glRenderbufferStorage); \
INIT_GLES_OR_OES(glBindRenderbuffer); \
INIT_GLES_OR_OES(glGetRenderbufferParameteriv); \
INIT_GLES_EXT(glDrawBuffers); \
INIT_GLES_FPE(glFogfv); \
INIT_GLES(glFogfv); \
INIT_GLES_FPE(glNormalPointer); \
INIT_GLES(glNormalPointer); \
INIT_GLES_FPE(glColorPointer); \
INIT_GLES(glColorPointer); \
INIT_GLES(glShaderBinary); \
INIT_GLES(glReleaseShaderCompiler); \
INIT_GLES(glCopyTexImage2D); \
INIT_GLES(glCopyTexSubImage2D); \
INIT_GLES(glGetFloatv); \
INIT_GLES(glGetClipPlanef); \
INIT_GLES_FPE(glMultiTexCoord4f); \
INIT_GLES(glMultiTexCoord4f); \
INIT_GLES(glSampleCoverage); \
INIT_GLES(glAlphaFuncx); \
INIT_GLES(glClearColor); \
INIT_GLES(glClearColorx); \
INIT_GLES(glClearDepthx); \
INIT_GLES(glClipPlanex); \
INIT_GLES(glColor4ub); \
INIT_GLES(glColor4x); \
INIT_GLES(glDepthRangex); \
INIT_GLES_OES(glDrawTexi); \
INIT_GLES(glFogCoordPointer); \
INIT_GLES(glFogCoordf); \
INIT_GLES(glFogCoordfv); \
INIT_GLES(glFogf); \
INIT_GLES(glFogx); \
INIT_GLES(glFogxv); \
INIT_GLES(glFrustumf); \
INIT_GLES(glFrustumx); \
INIT_GLES(glGetAttachedShaders); \
INIT_GLES(glGetBooleanv); \
INIT_GLES(glGetBufferParameteriv); \
INIT_GLES(glGetClipPlanex); \
INIT_GLES(glGetFixedv); \
INIT_GLES(glGetLightfv); \
INIT_GLES(glGetLightxv); \
INIT_GLES(glGetMaterialfv); \
INIT_GLES(glGetMaterialxv); \
INIT_GLES(glGetPointerv); \
INIT_GLES(glGetShaderSource); \
INIT_GLES(glGetTexEnvfv); \
INIT_GLES(glGetTexEnvxv); \
INIT_GLES(glGetTexParameterfv); \
INIT_GLES(glGetTexParameteriv); \
INIT_GLES(glGetTexParameterxv); \
INIT_GLES(glGetUniformfv); \
INIT_GLES(glGetUniformiv); \
INIT_GLES(glGetVertexAttribPointerv); \
INIT_GLES(glGetVertexAttribfv); \
INIT_GLES(glGetVertexAttribiv); \
INIT_GLES(glIsBuffer); \
INIT_GLES(glIsProgram); \
INIT_GLES_OES(glIsRenderbuffer); \
INIT_GLES(glIsShader); \
INIT_GLES(glIsTexture); \
INIT_GLES(glLightModelx); \
INIT_GLES(glLightModelxv); \
INIT_GLES(glLightf); \
INIT_GLES(glLightx); \
INIT_GLES(glLightxv); \
INIT_GLES(glLineWidth); \
INIT_GLES(glLineWidthx); \
INIT_GLES(glLoadMatrixx); \
INIT_GLES(glMaterialx); \
INIT_GLES(glMaterialxv); \
INIT_GLES(glMultMatrixf); \
INIT_GLES(glMultMatrixx); \
INIT_GLES_OES(glMultiDrawArrays); \
INIT_GLES_OES(glMultiDrawElements); \
INIT_GLES(glMultiTexCoord4x); \
INIT_GLES(glNormal3x); \
INIT_GLES(glOrthof); \
INIT_GLES(glOrthox); \
INIT_GLES(glPointParameterf); \
INIT_GLES(glPointParameterx); \
INIT_GLES(glPointParameterxv); \
INIT_GLES(glPointSizePointerOES); \
INIT_GLES(glPointSizex); \
INIT_GLES(glPolygonOffset); \
INIT_GLES(glPolygonOffsetx); \
INIT_GLES(glPopMatrix); \
INIT_GLES(glPushMatrix); \
INIT_GLES(glRotatef); \
INIT_GLES(glRotatex); \
INIT_GLES(glSampleCoveragex); \
INIT_GLES(glScalef); \
INIT_GLES(glScalex); \
INIT_GLES(glTexEnvi); \
INIT_GLES(glTexEnviv); \
INIT_GLES(glTexEnvx); \
INIT_GLES(glTexEnvxv); \
INIT_GLES(glTexParameterx); \
INIT_GLES(glTexParameterxv); \
INIT_GLES(glTranslatef); \
INIT_GLES(glTranslatex); \
INIT_GLES(glUniform1f); \
INIT_GLES(glUniform2f); \
INIT_GLES(glUniform2i); \
INIT_GLES(glUniform3f); \
INIT_GLES(glUniform3i); \
INIT_GLES(glUniform4f); \
INIT_GLES(glUniform4i); \
INIT_GLES(glVertexAttrib1f); \
INIT_GLES(glVertexAttrib1fv); \
INIT_GLES(glVertexAttrib2f); \
INIT_GLES(glVertexAttrib2fv); \
INIT_GLES(glVertexAttrib3f); \
INIT_GLES(glVertexAttrib3fv); \
INIT_GLES(glVertexAttrib4f); \


typedef struct gl_functions {
    ALL_FUNCTIONS();
} gl_functions;
extern gl_functions host_functions;
void init_gl_functions();
#undef INIT_GLES_FPE
#undef INIT_GLES
#undef INIT_GLES_OR_OES
#undef INIT_GLES_EXT
#undef INIT_GLES_OES
#undef INIT_EGL
